"""
training/export_esp32.py

Converts models/kws_int8.tflite into a C source/header pair
(model_data.cc / model_data.h) suitable for inclusion in an ESP-IDF
firmware project alongside TensorFlow Lite Micro.

Usage:
    python training/export_esp32.py
    python training/export_esp32.py --out esp32_export/
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))
import config  # noqa: E402
from logging_utils import get_logger  # noqa: E402

log = get_logger("EXPORT")

HEADER_TEMPLATE = """\
// Auto-generated by training/export_esp32.py — do not edit by hand.
// Source: {source_name} ({size_bytes} bytes)
#ifndef TINYWAKE_MODEL_DATA_H_
#define TINYWAKE_MODEL_DATA_H_

extern const unsigned char g_tinywake_model_data[];
extern const int g_tinywake_model_data_len;

#endif  // TINYWAKE_MODEL_DATA_H_
"""

CC_TEMPLATE = """\
// Auto-generated by training/export_esp32.py — do not edit by hand.
// Source: {source_name} ({size_bytes} bytes)
#include "model_data.h"

alignas(8) const unsigned char g_tinywake_model_data[] = {{
{byte_lines}
}};

const int g_tinywake_model_data_len = {size_bytes};
"""


def _format_bytes(data: bytes, per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def export(tflite_path: Path, out_dir: Path) -> None:
    if not tflite_path.exists():
        raise FileNotFoundError(f"{tflite_path} not found — run training/quantize.py first.")

    data = tflite_path.read_bytes()
    out_dir.mkdir(parents=True, exist_ok=True)

    header_path = out_dir / "model_data.h"
    cc_path = out_dir / "model_data.cc"

    header_path.write_text(HEADER_TEMPLATE.format(
        source_name=tflite_path.name, size_bytes=len(data),
    ))
    cc_path.write_text(CC_TEMPLATE.format(
        source_name=tflite_path.name,
        size_bytes=len(data),
        byte_lines=_format_bytes(data),
    ))

    log.info(f"wrote {header_path} ({len(data)} bytes represented)")
    log.info(f"wrote {cc_path}")
    log.info("Include model_data.h in your ESP-IDF firmware and pass "
              "g_tinywake_model_data / g_tinywake_model_data_len to "
              "tflite::GetModel(...).")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default=str(config.MODELS_DIR / "kws_int8.tflite"))
    parser.add_argument("--out", default=str(config.ROOT_DIR / "esp32_export"))
    args = parser.parse_args()

    export(Path(args.model), Path(args.out))


if __name__ == "__main__":
    main()
